# Task 1: Track the progress of COVID-19 vaccination

#### What vaccines are used and in which countries?
#### What country is vaccinated more people?
#### What country is vaccinated a larger percent from its population?

In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df = pd.read_csv("/Users/katie/Jedha/kaggle_projects/covid-vaccination-progress/country_vaccinations.csv")

In [64]:
df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Argentina,ARG,2020-12-29,700.0,NaN,NaN,NaN,0.00,NaN,NaN,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
1,Argentina,ARG,2020-12-30,NaN,NaN,NaN,15656.0,NaN,NaN,346.0,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
2,Argentina,ARG,2020-12-31,32013.0,NaN,NaN,15656.0,0.07,NaN,346.0,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
3,Argentina,ARG,2021-01-01,NaN,NaN,NaN,11070.0,NaN,NaN,245.0,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
4,Argentina,ARG,2021-01-02,NaN,NaN,NaN,8776.0,NaN,NaN,194.0,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...

In [9]:
df.shape

(1653, 15)

In [6]:
df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,1.070000e+03,8.410000e+02,3.660000e+02,8.560000e+02,1.590000e+03,1070.000000,841.000000,366.000000,1590.000000
mean,7.170394e+05,7.244409e+05,1.669585e+05,5.214871e+04,4.640226e+04,2.986374,3.048668,0.682896,1609.847799
std,2.273545e+06,2.012510e+06,4.630726e+05,1.401072e+05,1.305616e+05,6.069133,5.789155,1.987391,3333.197201
min,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,1.692700e+04,1.852900e+04,1.964750e+03,1.617500e+03,1.311250e+03,0.280000,0.260000,0.020000,267.000000
50%,7.829550e+04,9.786000e+04,8.957500e+03,7.730000e+03,5.380000e+03,0.980000,0.990000,0.090000,684.000000
75%,3.513472e+05,5.157740e+05,8.607100e+04,4.290975e+04,2.334700e+04,2.342500,2.220000,0.650000,1251.750000
max,2.354099e+07,1.990224e+07,3.481921e+06,1.561585e+06,1.126251e+06,49.130000,32.870000,16.740000,30869.000000

In [7]:
df.nunique()

country                                  63
iso_code                                 58
date                                     46
total_vaccinations                     1045
people_vaccinated                       813
people_fully_vaccinated                 326
daily_vaccinations_raw                  830
daily_vaccinations                     1319
total_vaccinations_per_hundred          447
people_vaccinated_per_hundred           382
people_fully_vaccinated_per_hundred      98
daily_vaccinations_per_million         1029
vaccines                                 12
source_name                              36
source_website                           59
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1653 entries, 0 to 1652
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              1653 non-null   object
 1   iso_code                             1471 non-null   object
 2   date                                 1653 non-null   object
 3   total_vaccinations                   1070 non-null   float64
 4   people_vaccinated                    841 non-null    float64
 5   people_fully_vaccinated              366 non-null    float64
 6   daily_vaccinations_raw               856 non-null    float64
 7   daily_vaccinations                   1590 non-null   float64
 8   total_vaccinations_per_hundred       1070 non-null   float64
 9   people_vaccinated_per_hundred        841 non-null    float64
 10  people_fully_vaccinated_per_hundred  366 non-null    float64
 11  daily_vaccinations_per_million       1590 non-null   float64
 12  vaccines                             1653 non-null   object
 13  source_name                          1653 non-null   object
 14  source_website                       1653 non-null   object
dtypes: float64(9), object(6)
memory usage: 193.8+ KB

In [10]:
df.isnull().sum(axis = 0)

country                                   0
iso_code                                182
date                                      0
total_vaccinations                      583
people_vaccinated                       812
people_fully_vaccinated                1287
daily_vaccinations_raw                  797
daily_vaccinations                       63
total_vaccinations_per_hundred          583
people_vaccinated_per_hundred           812
people_fully_vaccinated_per_hundred    1287
daily_vaccinations_per_million           63
vaccines                                  0
source_name                               0
source_website                            0
dtype: int64

In [11]:
display(100*df.isnull().sum()/df.shape[0])

country                                 0.000000
iso_code                               11.010284
date                                    0.000000
total_vaccinations                     35.269208
people_vaccinated                      49.122807
people_fully_vaccinated                77.858439
daily_vaccinations_raw                 48.215366
daily_vaccinations                      3.811252
total_vaccinations_per_hundred         35.269208
people_vaccinated_per_hundred          49.122807
people_fully_vaccinated_per_hundred    77.858439
daily_vaccinations_per_million          3.811252
vaccines                                0.000000
source_name                             0.000000
source_website                          0.000000
dtype: float64

In [16]:
#drop columns where percentage of null values exceeds 70%
df = df.drop(columns=['people_fully_vaccinated', 'people_fully_vaccinated_per_hundred'
                ])

In [20]:
#group by country

df_by_country = df.groupby('country').sum()
df_by_country

,total_vaccinations,people_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,daily_vaccinations_per_million
country,,,,,,,
Argentina,2837091.0,2065693.0,70100.0,328701.0,6.29,4.57,7273.0
Austria,1961308.0,0.0,127850.0,181061.0,21.76,0.00,20104.0
Bahrain,2403216.0,0.0,105165.0,114506.0,141.24,0.00,67294.0
Belgium,2412566.0,2406141.0,231167.0,209129.0,20.84,20.77,18047.0
Bermuda,4597.0,4597.0,0.0,3225.0,7.38,7.38,51787.0
...,...,...,...,...,...,...,...
Turkey,14144610.0,14144610.0,1522580.0,2024533.0,16.78,16.78,24006.0
United Arab Emirates,39185471.0,31009568.0,1876753.0,1789522.0,396.20,313.53,180933.0
United Kingdom,87715301.0,80027694.0,4960572.0,6107483.0,129.20,117.87,89965.0
United States,250154774.0,213395266.0,13308144.0,20109996.0,75.58,64.48,60753.0
Wales,2910486.0,2905532.0,201392.0,253285.0,92.32,92.16,80335.0

In [21]:
#group by vaccine

df_by_vaccine = df.groupby('vaccines').sum()
df_by_vaccine

,total_vaccinations,people_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,daily_vaccinations_per_million
vaccines,,,,,,,
"CNBG, Sinovac",62767000.0,0.0,0.0,18500785.0,4.35,0.00,12846.0
"Covaxin, Covishield",12035970.0,12035970.0,2029480.0,1972497.0,0.88,0.88,1430.0
Covishield,3800.0,3800.0,3800.0,3800.0,0.01,0.01,70.0
"Covishield, Sinopharm",112921.0,112921.0,7411.0,19138.0,114.83,114.83,194610.0
"Moderna, Pfizer/BioNTech",376743546.0,319645332.0,21727789.0,28446246.0,1128.15,955.83,703604.0
"Oxford/AstraZeneca, Pfizer/BioNTech",174751914.0,159383620.0,9855192.0,12286544.0,588.04,544.02,434553.0
Pfizer/BioNTech,73867012.0,64354171.0,5877491.0,6348884.0,772.57,588.70,874915.0
"Pfizer/BioNTech, Sinopharm",41588687.0,31009568.0,1981918.0,1904028.0,537.44,313.53,248227.0
"Pfizer/BioNTech, Sinopharm, Sputnik V",1240770.0,1240770.0,274893.0,169494.0,18.25,18.25,24909.0
"Pfizer/BioNTech, Sinovac",15968.0,15968.0,0.0,8846.0,4.18,4.18,23146.0
Sinovac,19387001.0,19387001.0,2811226.0,2863607.0,19.13,19.13,27721.0
Sputnik V,4717591.0,2065693.0,70100.0,1255727.0,7.59,4.57,13627.0

In [43]:
country_vaccine = df[['country', 'vaccines']]
country_vaccine

        country                             vaccines
0     Argentina                            Sputnik V
1     Argentina                            Sputnik V
2     Argentina                            Sputnik V
3     Argentina                            Sputnik V
4     Argentina                            Sputnik V
...         ...                                  ...
1648      Wales  Oxford/AstraZeneca, Pfizer/BioNTech
1649      Wales  Oxford/AstraZeneca, Pfizer/BioNTech
1650      Wales  Oxford/AstraZeneca, Pfizer/BioNTech
1651      Wales  Oxford/AstraZeneca, Pfizer/BioNTech
1652      Wales  Oxford/AstraZeneca, Pfizer/BioNTech

[1653 rows x 2 columns]

In [28]:
df['vaccines'].value_counts()

Pfizer/BioNTech                          807
Moderna, Pfizer/BioNTech                 376
Oxford/AstraZeneca, Pfizer/BioNTech      211
Sputnik V                                 60
Pfizer/BioNTech, Sinopharm                52
CNBG, Sinovac                             44
Sinovac                                   43
Pfizer/BioNTech, Sinopharm, Sputnik V     19
Covishield, Sinopharm                     18
Covaxin, Covishield                       12
Pfizer/BioNTech, Sinovac                   9
Covishield                                 2
Name: vaccines, dtype: int64

In [35]:
df.groupby('vaccines').count()

,country,iso_code,date,total_vaccinations,people_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,daily_vaccinations_per_million,source_name,source_website
vaccines,,,,,,,,,,,,
"CNBG, Sinovac",44,44,44,6,0,0,43,6,0,43,44,44
"Covaxin, Covishield",12,12,12,12,12,11,11,12,12,11,12,12
Covishield,2,2,2,2,2,1,1,2,2,1,2,2
"Covishield, Sinopharm",18,18,18,10,10,4,17,10,10,17,18,18
"Moderna, Pfizer/BioNTech",376,376,376,284,260,244,364,284,260,364,376,376
"Oxford/AstraZeneca, Pfizer/BioNTech",211,38,211,99,99,74,206,99,99,206,211,211
Pfizer/BioNTech,807,807,807,542,386,433,774,542,386,774,807,807
"Pfizer/BioNTech, Sinopharm",52,52,52,51,18,48,50,51,18,50,52,52
"Pfizer/BioNTech, Sinopharm, Sputnik V",19,19,19,10,10,6,18,10,10,18,19,19
"Pfizer/BioNTech, Sinovac",9,0,9,3,3,0,8,3,3,8,9,9
Sinovac,43,43,43,33,33,28,40,33,33,40,43,43
Sputnik V,60,60,60,18,8,7,58,18,8,58,60,60

In [46]:
pd.set_option('display.max_rows', None)

# What vaccines are used in which countries?:

In [47]:
df.groupby(["country", "vaccines"]).size()

country               vaccines
Argentina             Sputnik V                                30
Austria               Pfizer/BioNTech                          23
Bahrain               Pfizer/BioNTech, Sinopharm               29
Belgium               Moderna, Pfizer/BioNTech                 30
Bermuda               Pfizer/BioNTech                          14
Brazil                Sinovac                                  12
Bulgaria              Moderna, Pfizer/BioNTech                 29
Canada                Moderna, Pfizer/BioNTech                 40
Chile                 Pfizer/BioNTech                          34
China                 CNBG, Sinovac                            44
Costa Rica            Pfizer/BioNTech                          33
Croatia               Pfizer/BioNTech                          27
Cyprus                Pfizer/BioNTech                          17
Czechia               Moderna, Pfizer/BioNTech                 31
Denmark               Moderna, Pfizer/BioNTech                 31
Ecuador               Pfizer/BioNTech                           2
England               Oxford/AstraZeneca, Pfizer/BioNTech      38
Estonia               Pfizer/BioNTech                          31
Finland               Pfizer/BioNTech                          28
France                Pfizer/BioNTech                          40
Germany               Moderna, Pfizer/BioNTech                 31
Gibraltar             Pfizer/BioNTech                          17
Greece                Pfizer/BioNTech                          31
Hungary               Pfizer/BioNTech                          30
Iceland               Moderna, Pfizer/BioNTech                 29
India                 Covaxin, Covishield                      12
Indonesia             Sinovac                                  16
Ireland               Pfizer/BioNTech                          25
Isle of Man           Pfizer/BioNTech                           7
Israel                Moderna, Pfizer/BioNTech                 40
Italy                 Pfizer/BioNTech                          32
Kuwait                Pfizer/BioNTech                           1
Latvia                Pfizer/BioNTech                          30
Lithuania             Moderna, Pfizer/BioNTech                 31
Luxembourg            Pfizer/BioNTech                          28
Malta                 Pfizer/BioNTech                          30
Mexico                Pfizer/BioNTech                          34
Myanmar               Covishield                                2
Netherlands           Moderna, Pfizer/BioNTech                 22
Northern Cyprus       Pfizer/BioNTech, Sinovac                  9
Northern Ireland      Oxford/AstraZeneca, Pfizer/BioNTech      45
Norway                Pfizer/BioNTech                          31
Oman                  Pfizer/BioNTech                          30
Panama                Pfizer/BioNTech                           6
Poland                Pfizer/BioNTech                          30
Portugal              Pfizer/BioNTech                          31
Romania               Pfizer/BioNTech                          31
Russia                Sputnik V                                30
Saudi Arabia          Pfizer/BioNTech                          12
Scotland              Oxford/AstraZeneca, Pfizer/BioNTech      45
Serbia                Pfizer/BioNTech, Sinopharm, Sputnik V    19
Seychelles            Covishield, Sinopharm                    18
Singapore             Pfizer/BioNTech                          12
Slovakia              Pfizer/BioNTech                          23
Slovenia              Pfizer/BioNTech                          24
Spain                 Moderna, Pfizer/BioNTech                 24
Sweden                Pfizer/BioNTech                          30
Switzerland           Pfizer/BioNTech                          33
Turkey                Sinovac                                  15
United Arab Emirates  Pfizer/BioNTech, Sinopharm               23
United Kingdom        Oxford/AstraZeneca, Pfizer/BioNTech      38
United States         Moderna, Pfizer/BioNTech                 38
Wales                 Oxford/AstraZeneca, Pfizer/BioNTech      45
dtype: int64

In [54]:
bahrain = df.loc[df['country'] == 'Bahrain'] 
bahrain

,country,iso_code,date,total_vaccinations,people_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
53,Bahrain,BHR,2020-12-23,38965.0,NaN,NaN,NaN,2.29,NaN,NaN,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
54,Bahrain,BHR,2020-12-24,50071.0,NaN,11106.0,11106.0,2.94,NaN,6527.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
55,Bahrain,BHR,2020-12-25,50543.0,NaN,472.0,5789.0,2.97,NaN,3402.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
56,Bahrain,BHR,2020-12-26,51556.0,NaN,1013.0,4197.0,3.03,NaN,2467.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
57,Bahrain,BHR,2020-12-27,53614.0,NaN,2058.0,3662.0,3.15,NaN,2152.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
58,Bahrain,BHR,2020-12-28,55014.0,NaN,1400.0,3210.0,3.23,NaN,1886.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
59,Bahrain,BHR,2020-12-29,56041.0,NaN,1027.0,2846.0,3.29,NaN,1673.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
60,Bahrain,BHR,2020-12-30,57317.0,NaN,1276.0,2622.0,3.37,NaN,1541.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
61,Bahrain,BHR,2020-12-31,58643.0,NaN,1326.0,1225.0,3.45,NaN,720.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
62,Bahrain,BHR,2021-01-01,59351.0,NaN,708.0,1258.0,3.49,NaN,739.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
63,Bahrain,BHR,2021-01-02,60097.0,NaN,746.0,1220.0,3.53,NaN,717.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
64,Bahrain,BHR,2021-01-03,60689.0,NaN,592.0,1011.0,3.57,NaN,594.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
65,Bahrain,BHR,2021-01-04,61612.0,NaN,923.0,943.0,3.62,NaN,554.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
66,Bahrain,BHR,2021-01-05,63893.0,NaN,2281.0,1122.0,3.75,NaN,659.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
67,Bahrain,BHR,2021-01-06,68472.0,NaN,4579.0,1594.0,4.02,NaN,937.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
68,Bahrain,BHR,2021-01-07,72239.0,NaN,3767.0,1942.0,4.25,NaN,1141.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
69,Bahrain,BHR,2021-01-08,78291.0,NaN,6052.0,2706.0,4.60,NaN,1590.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
70,Bahrain,BHR,2021-01-09,84157.0,NaN,5866.0,3437.0,4.95,NaN,2020.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
71,Bahrain,BHR,2021-01-10,89250.0,NaN,5093.0,4080.0,5.25,NaN,2398.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
72,Bahrain,BHR,2021-01-11,92598.0,NaN,3348.0,4427.0,5.44,NaN,2602.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
73,Bahrain,BHR,2021-01-12,97776.0,NaN,5178.0,4840.0,5.75,NaN,2844.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
74,Bahrain,BHR,2021-01-13,101363.0,NaN,3587.0,4699.0,5.96,NaN,2762.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
75,Bahrain,BHR,2021-01-14,109566.0,NaN,8203.0,5332.0,6.44,NaN,3134.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
76,Bahrain,BHR,2021-01-15,122819.0,NaN,13253.0,6361.0,7.22,NaN,3738.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
77,Bahrain,BHR,2021-01-16,137159.0,NaN,14340.0,7572.0,8.06,NaN,4450.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
78,Bahrain,BHR,2021-01-17,141563.0,NaN,4404.0,7473.0,8.32,NaN,4392.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
79,Bahrain,BHR,2021-01-18,142831.0,NaN,1268.0,7176.0,8.39,NaN,4217.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
80,Bahrain,BHR,2021-01-19,143596.0,NaN,765.0,6546.0,8.44,NaN,3847.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...
81,Bahrain,BHR,2021-01-20,144130.0,NaN,534.0,6110.0,8.47,NaN,3591.0,"Pfizer/BioNTech, Sinopharm",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1351989...

In [61]:
bahrain['vaccines'].value_counts()

Pfizer/BioNTech, Sinopharm    29
Name: vaccines, dtype: int64

# Which country vaccinated the most people?:

In [70]:
df_by_country.reset_index(level=0, inplace=True)
df_by_country

,index,country,total_vaccinations,people_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,daily_vaccinations_per_million
0,0,Argentina,2837091.0,2065693.0,70100.0,328701.0,6.29,4.57,7273.0
1,1,Austria,1961308.0,0.0,127850.0,181061.0,21.76,0.00,20104.0
2,2,Bahrain,2403216.0,0.0,105165.0,114506.0,141.24,0.00,67294.0
3,3,Belgium,2412566.0,2406141.0,231167.0,209129.0,20.84,20.77,18047.0
4,4,Bermuda,4597.0,4597.0,0.0,3225.0,7.38,7.38,51787.0
5,5,Brazil,4245502.0,4245502.0,1129885.0,620000.0,1.99,1.99,2917.0
6,6,Bulgaria,407473.0,370417.0,25875.0,29244.0,5.87,5.33,4210.0
7,7,Canada,6555693.0,887153.0,489020.0,523663.0,17.37,2.35,13873.0
8,8,Chile,609767.0,507998.0,61484.0,72313.0,3.19,2.66,3784.0
9,9,China,62767000.0,0.0,0.0,18500785.0,4.35,0.00,12846.0
10,10,Costa Rica,114637.0,99768.0,0.0,40764.0,2.25,1.96,8002.0
11,11,Croatia,458765.0,381907.0,20750.0,58762.0,11.17,9.30,14312.0
12,12,Cyprus,37541.0,15322.0,0.0,12047.0,4.29,1.75,13754.0
13,13,Czechia,2619608.0,2529575.0,221200.0,200895.0,24.45,23.61,18759.0
14,14,Denmark,3713177.0,3559302.0,209494.0,212129.0,64.11,61.47,36624.0
15,15,Ecuador,108.0,108.0,108.0,108.0,0.00,0.00,6.0
16,16,England,76513130.0,69251661.0,4332097.0,5341703.0,135.95,123.04,94897.0
17,17,Estonia,397661.0,0.0,29357.0,26874.0,30.00,0.00,20259.0
18,18,Finland,857802.0,333700.0,86719.0,103464.0,15.50,6.02,18674.0
19,19,France,9827810.0,9803592.0,1136890.0,939994.0,14.49,14.45,13857.0
20,20,Germany,26083182.0,24518326.0,1966621.0,1795158.0,31.13,29.27,21425.0
21,21,Gibraltar,100248.0,100248.0,8019.0,11945.0,297.55,297.55,354548.0
22,22,Greece,1897155.0,1847497.0,187881.0,169486.0,18.21,17.73,16260.0
23,23,Hungary,2269199.0,1271060.0,134041.0,156918.0,23.48,13.15,16244.0
24,24,Iceland,41822.0,31735.0,0.0,8016.0,12.26,9.31,23497.0
25,25,India,12035970.0,12035970.0,2029480.0,1972497.0,0.88,0.88,1430.0
26,26,Indonesia,996889.0,996889.0,158761.0,219074.0,0.36,0.36,798.0
27,27,Ireland,497317.0,0.0,0.0,125638.0,10.08,0.00,25441.0
28,28,Isle of Man,21888.0,12694.0,1468.0,1150.0,25.74,14.92,13524.0
29,29,Israel,69855274.0,58918523.0,4252811.0,3829195.0,807.08,680.72,442398.0
30,30,Italy,23938340.0,22957585.0,1568272.0,1433568.0,39.56,37.93,23710.0
31,31,Kuwait,2500.0,0.0,0.0,0.0,0.06,0.00,0.0
32,32,Latvia,280599.0,0.0,18576.0,20703.0,14.88,0.00,10976.0
33,33,Lithuania,951109.0,886334.0,66945.0,72230.0,34.91,32.55,26531.0
34,34,Luxembourg,56406.0,53916.0,5403.0,6750.0,9.02,8.62,10782.0
35,35,Malta,187487.0,0.0,10666.0,19514.0,42.46,0.00,44200.0
36,36,Mexico,7750093.0,7569136.0,626533.0,603992.0,6.03,5.87,4684.0
37,37,Myanmar,3800.0,3800.0,3800.0,3800.0,0.01,0.01,70.0
38,38,Netherlands,1276037.0,0.0,79744.0,171236.0,7.46,0.00,9994.0
39,39,Northern Cyprus,15968.0,15968.0,0.0,8846.0,4.18,4.18,23146.0
40,40,Northern Ireland,2643358.0,2293932.0,99096.0,180992.0,139.60,121.16,95579.0
41,41,Norway,1067446.0,1051339.0,83878.0,80229.0,19.70,19.38,14800.0
42,42,Oman,485716.0,439847.0,32078.0,34835.0,9.50,8.64,6823.0
43,43,Panama,19829.0,19829.0,6420.0,5746.0,0.46,0.46,1332.0
44,44,Poland,10136461.0,9717481.0,900666.0,747605.0,26.78,25.69,19754.0
45,45,Portugal,1285051.0,523913.0,57661.0,262375.0,12.59,5.13,25731.0
46,46,Romania,5733585.0,5552183.0,568638.0,458038.0,29.79,28.84,23806.0
47,47,Russia,1880500.0,0.0,0.0,927026.0,1.30,0.00,6354.0
48,48,Saudi Arabia,711729.0,0.0,37862.0,211705.0,2.05,0.00,6082.0
49,49,Scotland,4969639.0,4904801.0,262035.0,403081.0,90.97,89.79,73777.0
50,50,Serbia,1240770.0,1240770.0,274893.0,169494.0,18.25,18.25,24909.0
51,51,Seychelles,112921.0,112921.0,7411.0,19138.0,114.83,114.83,194610.0
52,52,Singapore,69600.0,69600.0,2800.0,52490.0,1.20,1.20,8974.0
53,53,Slovakia,1271889.0,1247791.0,108426.0,106141.0,23.31,22.87,19441.0
54,54,Slovenia,817142.0,773060.0,55045.0,54449.0,39.32,37.20,26189.0
55,55,Spain,12672831.0,12142560.0,876768.0,1285355.0,27.09,25.97,27493.0
56,56,Sweden,454185.0,0.0,0.0,182939.0,4.50,0.00,18111.0
57,57,Switzerland,543151.0,0.0,0.0,164056.0,6.27,0.00,18964.0
58,58,Turkey,14144610.0,14144610.0,1522580.0,2024533.0,16.78,16.78,24006.0
59,59,United Arab Emirates,39185471.0,31009568.0,1876753.0,1789522.0,396.20,313.53,180933.0
60,60,United Kingdom,87715301.0,80027694.0,4960572.0,6107483.0,129.20,117.87,89965.0
61,61,United States,250154774.0,213395266.0,13308144.0,20109996.0,75.58,64.48,60753.0
62,62,Wales,2910486.0,2905532.0,201392.0,253285.0,92.32,92.16,80335.0

In [72]:
country_people = df_by_country[['country', 'people_vaccinated']]

In [73]:
country_people.sort_values('people_vaccinated', ascending=False)

                 country  people_vaccinated
61         United States        213395266.0
60        United Kingdom         80027694.0
16               England         69251661.0
29                Israel         58918523.0
59  United Arab Emirates         31009568.0
20               Germany         24518326.0
30                 Italy         22957585.0
58                Turkey         14144610.0
55                 Spain         12142560.0
25                 India         12035970.0
19                France          9803592.0
44                Poland          9717481.0
36                Mexico          7569136.0
46               Romania          5552183.0
49              Scotland          4904801.0
5                 Brazil          4245502.0
14               Denmark          3559302.0
62                 Wales          2905532.0
13               Czechia          2529575.0
3                Belgium          2406141.0
40      Northern Ireland          2293932.0
0              Argentina          2065693.0
22                Greece          1847497.0
23               Hungary          1271060.0
53              Slovakia          1247791.0
50                Serbia          1240770.0
41                Norway          1051339.0
26             Indonesia           996889.0
7                 Canada           887153.0
33             Lithuania           886334.0
54              Slovenia           773060.0
45              Portugal           523913.0
8                  Chile           507998.0
42                  Oman           439847.0
11               Croatia           381907.0
6               Bulgaria           370417.0
18               Finland           333700.0
51            Seychelles           112921.0
21             Gibraltar           100248.0
10            Costa Rica            99768.0
52             Singapore            69600.0
34            Luxembourg            53916.0
24               Iceland            31735.0
43                Panama            19829.0
39       Northern Cyprus            15968.0
12                Cyprus            15322.0
28           Isle of Man            12694.0
4                Bermuda             4597.0
37               Myanmar             3800.0
15               Ecuador              108.0
27               Ireland                0.0
57           Switzerland                0.0
56                Sweden                0.0
2                Bahrain                0.0
48          Saudi Arabia                0.0
9                  China                0.0
35                 Malta                0.0
47                Russia                0.0
17               Estonia                0.0
1                Austria                0.0
32                Latvia                0.0
38           Netherlands                0.0
31                Kuwait                0.0

# What country is vaccinated a larger percent from its population?

In [75]:
country_population = df_by_country[['country', 'people_vaccinated_per_hundred']]
country_people.sort_values('people_vaccinated', ascending=False)

                 country  people_vaccinated
61         United States        213395266.0
60        United Kingdom         80027694.0
16               England         69251661.0
29                Israel         58918523.0
59  United Arab Emirates         31009568.0
20               Germany         24518326.0
30                 Italy         22957585.0
58                Turkey         14144610.0
55                 Spain         12142560.0
25                 India         12035970.0
19                France          9803592.0
44                Poland          9717481.0
36                Mexico          7569136.0
46               Romania          5552183.0
49              Scotland          4904801.0
5                 Brazil          4245502.0
14               Denmark          3559302.0
62                 Wales          2905532.0
13               Czechia          2529575.0
3                Belgium          2406141.0
40      Northern Ireland          2293932.0
0              Argentina          2065693.0
22                Greece          1847497.0
23               Hungary          1271060.0
53              Slovakia          1247791.0
50                Serbia          1240770.0
41                Norway          1051339.0
26             Indonesia           996889.0
7                 Canada           887153.0
33             Lithuania           886334.0
54              Slovenia           773060.0
45              Portugal           523913.0
8                  Chile           507998.0
42                  Oman           439847.0
11               Croatia           381907.0
6               Bulgaria           370417.0
18               Finland           333700.0
51            Seychelles           112921.0
21             Gibraltar           100248.0
10            Costa Rica            99768.0
52             Singapore            69600.0
34            Luxembourg            53916.0
24               Iceland            31735.0
43                Panama            19829.0
39       Northern Cyprus            15968.0
12                Cyprus            15322.0
28           Isle of Man            12694.0
4                Bermuda             4597.0
37               Myanmar             3800.0
15               Ecuador              108.0
27               Ireland                0.0
57           Switzerland                0.0
56                Sweden                0.0
2                Bahrain                0.0
48          Saudi Arabia                0.0
9                  China                0.0
35                 Malta                0.0
47                Russia                0.0
17               Estonia                0.0
1                Austria                0.0
32                Latvia                0.0
38           Netherlands                0.0
31                Kuwait                0.0